### ISSUE TITLE
Menu Cheese burger on windows

### ISSUE THREAD

**Issue by Scantron445** [zbonfo/qrwaiter#2]
When attempting to change the temperature and cheese for the cheeseburger met with an error
![error menu well done](https://user-images.githubusercontent.com/130017210/235549093-438795de-99a1-4551-b0d0-b306c0157136.PNG)

**Comment by Scantron445** [comment]
Same type of error for Pizza toppings and size
![error menu 2](https://user-images.githubusercontent.com/130017210/235549472-273faf7a-ac0b-445e-8b62-fb38bad319a8.PNG)

**Comment by Scantron445** [comment]
Same errors occur for Apple iphone

**Comment by 5rahim** [comment]
Solved
